
#ifndef OPCODE_TABLE_HPP
#define OPCODE_TABLE_HPP

#include "Cpu65816.hpp"

OpCode Cpu65816::OP_CODE_TABLE[] = {
    OpCode(0x00, "BRK", Interrupt,                                      &Cpu65816::executeInterrupt),
    OpCode(0x01, "ORA", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeORA),
    OpCode(0x02, "COP", Interrupt,                                      &Cpu65816::executeInterrupt),
    OpCode(0x03, "ORA", StackRelative,                                  &Cpu65816::executeORA),
    OpCode(0x04, "TSB", DirectPage,                                     &Cpu65816::executeTSBTRB),
    OpCode(0x05, "ORA", DirectPage,                                     &Cpu65816::executeORA),
    OpCode(0x06, "ASL", DirectPage,                                     &Cpu65816::executeASL),
    OpCode(0x07, "ORA", DirectPageIndirectLong,                         &Cpu65816::executeORA),
    OpCode(0x08, "PHP", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x09, "ORA", Immediate,                                      &Cpu65816::executeORA),
    OpCode(0x0A, "ASL", Accumulator,                                    &Cpu65816::executeASL),
    OpCode(0x0B, "PHD", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x0C, "TSB", Absolute,                                       &Cpu65816::executeTSBTRB),
    OpCode(0x0D, "ORA", Absolute,                                       &Cpu65816::executeORA),
    OpCode(0x0E, "ASL", Absolute,                                       &Cpu65816::executeASL),
    OpCode(0x0F, "ORA", AbsoluteLong,                                   &Cpu65816::executeORA),
    OpCode(0x10, "BPL", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x11, "ORA", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeORA),
    OpCode(0x12, "ORA", DirectPageIndirect,                             &Cpu65816::executeORA),
    OpCode(0x13, "ORA", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeORA),
    OpCode(0x14, "TRB", DirectPage,                                     &Cpu65816::executeTSBTRB),
    OpCode(0x15, "ORA", DirectPageIndexedWithX,                         &Cpu65816::executeORA),
    OpCode(0x16, "ASL", DirectPageIndexedWithX,                         &Cpu65816::executeASL),
    OpCode(0x17, "ORA", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeORA),
    OpCode(0x18, "CLC", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0x19, "ORA", AbsoluteIndexedWithY,                           &Cpu65816::executeORA),
    OpCode(0x1A, "INC", Accumulator,                                    &Cpu65816::executeINCDEC),
    OpCode(0x1B, "TCS", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x1C, "TRB", Absolute,                                       &Cpu65816::executeTSBTRB),
    OpCode(0x1D, "ORA", AbsoluteIndexedWithX,                           &Cpu65816::executeORA),
    OpCode(0x1E, "ASL", AbsoluteIndexedWithX,                           &Cpu65816::executeASL),
    OpCode(0x1F, "ORA", AbsoluteLongIndexedWithX,                       &Cpu65816::executeORA),
    OpCode(0x20, "JSR", Absolute,                                       &Cpu65816::executeJumpReturn),
    OpCode(0x21, "AND", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeAND),
    OpCode(0x22, "JSR", AbsoluteLong,                                   &Cpu65816::executeJumpReturn),
    OpCode(0x23, "AND", StackRelative,                                  &Cpu65816::executeAND),
    OpCode(0x24, "BIT", DirectPage),
    OpCode(0x25, "AND", DirectPage,                                     &Cpu65816::executeAND),
    OpCode(0x26, "ROL", DirectPage,                                     &Cpu65816::executeROL),
    OpCode(0x27, "AND", DirectPageIndirectLong,                         &Cpu65816::executeAND),
    OpCode(0x28, "PLP", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x29, "AND", Immediate,                                      &Cpu65816::executeAND),
    OpCode(0x2A, "ROL", Accumulator,                                    &Cpu65816::executeROL),
    OpCode(0x2B, "PLD", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x2C, "BIT", Absolute),
    OpCode(0x2D, "AND", Absolute,                                       &Cpu65816::executeAND),
    OpCode(0x2E, "ROL", Absolute,                                       &Cpu65816::executeROL),
    OpCode(0x2F, "AND", AbsoluteLong,                                   &Cpu65816::executeAND),
    OpCode(0x30, "BMI", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x31, "AND", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeAND),
    OpCode(0x32, "AND", DirectPageIndirect,                             &Cpu65816::executeAND),
    OpCode(0x33, "AND", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeAND),
    OpCode(0x34, "BIT", DirectPageIndexedWithX),
    OpCode(0x35, "AND", DirectPageIndexedWithX,                         &Cpu65816::executeAND),
    OpCode(0x36, "ROL", DirectPageIndexedWithX,                         &Cpu65816::executeROL),
    OpCode(0x37, "AND", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeAND),
    OpCode(0x38, "SEC", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0x39, "AND", AbsoluteIndexedWithY,                           &Cpu65816::executeAND),
    OpCode(0x3A, "DEC", Accumulator,                                    &Cpu65816::executeINCDEC),
    OpCode(0x3B, "TSC", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x3C, "BIT", AbsoluteIndexedWithX),
    OpCode(0x3D, "AND", AbsoluteIndexedWithX,                           &Cpu65816::executeAND),
    OpCode(0x3E, "ROL", AbsoluteIndexedWithX,                           &Cpu65816::executeROL),
    OpCode(0x3F, "AND", AbsoluteLongIndexedWithX,                       &Cpu65816::executeAND),
    OpCode(0x40, "RTI", StackImplied,                                   &Cpu65816::executeInterrupt),
    OpCode(0x41, "EOR", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeEOR),
    OpCode(0x42, "WDM", Implied),
    OpCode(0x43, "EOR", StackRelative,                                  &Cpu65816::executeEOR),
    OpCode(0x44, "MVP", BlockMove),
    OpCode(0x45, "EOR", DirectPage,                                     &Cpu65816::executeEOR),
    OpCode(0x46, "LSR", DirectPage),
    OpCode(0x47, "EOR", DirectPageIndirectLong,                         &Cpu65816::executeEOR),
    OpCode(0x48, "PHA", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x49, "EOR", Immediate,                                      &Cpu65816::executeEOR),
    OpCode(0x4A, "LSR", Accumulator),
    OpCode(0x4B, "PHK", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x4C, "JMP", Absolute,                                       &Cpu65816::executeJumpReturn),
    OpCode(0x4D, "EOR", Absolute,                                       &Cpu65816::executeEOR),
    OpCode(0x4E, "LSR", Absolute),
    OpCode(0x4F, "EOR", AbsoluteLong,                                   &Cpu65816::executeEOR),
    OpCode(0x50, "BVC", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x51, "EOR", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeEOR),
    OpCode(0x52, "EOR", DirectPageIndirect,                             &Cpu65816::executeEOR),
    OpCode(0x53, "EOR", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeEOR),
    OpCode(0x54, "MVN", BlockMove),
    OpCode(0x55, "EOR", DirectPageIndexedWithX,                         &Cpu65816::executeEOR),
    OpCode(0x56, "LSR", DirectPageIndexedWithX),
    OpCode(0x57, "EOR", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeEOR),
    OpCode(0x58, "CLI", Implied),
    OpCode(0x59, "EOR", AbsoluteIndexedWithY,                           &Cpu65816::executeEOR),
    OpCode(0x5A, "PHY", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x5B, "TCD", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x5C, "JMP", AbsoluteLong,                                   &Cpu65816::executeJumpReturn),
    OpCode(0x5D, "EOR", AbsoluteIndexedWithX,                           &Cpu65816::executeEOR),
    OpCode(0x5E, "LSR", AbsoluteIndexedWithX),
    OpCode(0x5F, "EOR", AbsoluteLongIndexedWithX,                       &Cpu65816::executeEOR),
    OpCode(0x60, "RTS", StackImplied,                                   &Cpu65816::executeJumpReturn),
    OpCode(0x61, "ADC", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeADC),
    OpCode(0x62, "PER", StackProgramCounterRelativeLong,                &Cpu65816::executeStack),
    OpCode(0x63, "ADC", StackRelative,                                  &Cpu65816::executeADC),
    OpCode(0x64, "STZ", DirectPage,                                     &Cpu65816::executeSTZ),
    OpCode(0x65, "ADC", DirectPage,                                     &Cpu65816::executeADC),
    OpCode(0x66, "ROR", DirectPage,                                     &Cpu65816::executeROR),
    OpCode(0x67, "ADC", DirectPageIndirectLong,                         &Cpu65816::executeADC),
    OpCode(0x68, "PLA", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x69, "ADC", Immediate,                                      &Cpu65816::executeADC),
    OpCode(0x6A, "ROR", Accumulator,                                    &Cpu65816::executeROR),
    OpCode(0x6B, "RTL", StackImplied,                                   &Cpu65816::executeJumpReturn),
    OpCode(0x6C, "JMP", AbsoluteIndirect,                               &Cpu65816::executeJumpReturn),
    OpCode(0x6D, "ADC", Absolute,                                       &Cpu65816::executeADC),
    OpCode(0x6E, "ROR", Absolute,                                       &Cpu65816::executeROR),
    OpCode(0x6F, "ADC", AbsoluteLong,                                   &Cpu65816::executeADC),
    OpCode(0x70, "BVS", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x71, "ADC", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeADC),
    OpCode(0x72, "ADC", DirectPageIndirect,                             &Cpu65816::executeADC),
    OpCode(0x73, "ADC", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeADC),
    OpCode(0x74, "STZ", DirectPageIndexedWithX,                         &Cpu65816::executeSTZ),
    OpCode(0x75, "ADC", DirectPageIndexedWithX,                         &Cpu65816::executeADC),
    OpCode(0x76, "ROR", DirectPageIndexedWithX,                         &Cpu65816::executeROR),
    OpCode(0x77, "ADC", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeADC),
    OpCode(0x78, "SEI", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0x79, "ADC", AbsoluteIndexedWithY,                           &Cpu65816::executeADC),
    OpCode(0x7A, "PLY", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x7B, "TDC", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x7C, "JMP", AbsoluteIndexedIndirectWithX,                   &Cpu65816::executeJumpReturn),
    OpCode(0x7D, "ADC", AbsoluteIndexedWithX,                           &Cpu65816::executeADC),
    OpCode(0x7E, "ROR", AbsoluteIndexedWithX,                           &Cpu65816::executeROR),
    OpCode(0x7F, "ADC", AbsoluteLongIndexedWithX,                       &Cpu65816::executeADC),
    OpCode(0x80, "BRA", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x81, "STA", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeSTA),
    OpCode(0x82, "BRL", ProgramCounterRelativeLong,                     &Cpu65816::executeBranch),
    OpCode(0x83, "STA", StackRelative,                                  &Cpu65816::executeSTA),
    OpCode(0x84, "STY", DirectPage,                                     &Cpu65816::executeSTY),
    OpCode(0x85, "STA", DirectPage,                                     &Cpu65816::executeSTA),
    OpCode(0x86, "STX", DirectPage,                                     &Cpu65816::executeSTX),
    OpCode(0x87, "STA", DirectPageIndirectLong,                         &Cpu65816::executeSTA),
    OpCode(0x88, "DEY", Implied,                                        &Cpu65816::executeINCDEC),
    OpCode(0x89, "BIT", Immediate),
    OpCode(0x8A, "TXA", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x8B, "PHB", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0x8C, "STY", Absolute,                                       &Cpu65816::executeSTY),
    OpCode(0x8D, "STA", Absolute,                                       &Cpu65816::executeSTA),
    OpCode(0x8E, "STX", Absolute,                                       &Cpu65816::executeSTX),
    OpCode(0x8F, "STA", AbsoluteLong,                                   &Cpu65816::executeSTA),
    OpCode(0x90, "BCC", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0x91, "STA", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeSTA),
    OpCode(0x92, "STA", DirectPageIndirect,                             &Cpu65816::executeSTA),
    OpCode(0x93, "STA", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeSTA),
    OpCode(0x94, "STY", DirectPageIndexedWithX,                         &Cpu65816::executeSTY),
    OpCode(0x95, "STAX", DirectPageIndexedWithX),
    OpCode(0x96, "STX", DirectPageIndexedWithY,                         &Cpu65816::executeSTX),
    OpCode(0x97, "STA", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeSTA),
    OpCode(0x98, "TYA", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x99, "STA", AbsoluteIndexedWithY,                           &Cpu65816::executeSTA),
    OpCode(0x9A, "TXS", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x9B, "TXY", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0x9C, "STZ", Absolute,                                       &Cpu65816::executeSTZ),
    OpCode(0x9D, "STA", AbsoluteIndexedWithX,                           &Cpu65816::executeSTA),
    OpCode(0x9E, "STZ", AbsoluteIndexedWithX,                           &Cpu65816::executeSTZ),
    OpCode(0x9F, "STA", AbsoluteLongIndexedWithX,                       &Cpu65816::executeSTA),
    OpCode(0xA0, "LDY", Immediate,                                      &Cpu65816::executeLDY),
    OpCode(0xA1, "LDA", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeLDA),
    OpCode(0xA2, "LDX", Immediate,                                      &Cpu65816::executeLDX),
    OpCode(0xA3, "LDA", StackRelative,                                  &Cpu65816::executeLDA),
    OpCode(0xA4, "LDY", DirectPage,                                     &Cpu65816::executeLDY),
    OpCode(0xA5, "LDA", DirectPage,                                     &Cpu65816::executeLDA),
    OpCode(0xA6, "LDX", DirectPage,                                     &Cpu65816::executeLDX),
    OpCode(0xA7, "LDA", DirectPageIndirectLong,                         &Cpu65816::executeLDA),
    OpCode(0xA8, "TAY", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0xA9, "LDA", Immediate,                                      &Cpu65816::executeLDA),
    OpCode(0xAA, "TAX", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0xAB, "PLB", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0xAC, "LDY", Absolute,                                       &Cpu65816::executeLDY),
    OpCode(0xAD, "LDA", Absolute,                                       &Cpu65816::executeLDA),
    OpCode(0xAE, "LDX", Absolute,                                       &Cpu65816::executeLDX),
    OpCode(0xAF, "LDA", AbsoluteLong,                                   &Cpu65816::executeLDA),
    OpCode(0xB0, "BCS", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0xB1, "LDA", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeLDA),
    OpCode(0xB2, "LDA", DirectPageIndirect,                             &Cpu65816::executeLDA),
    OpCode(0xB3, "LDA", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeLDA),
    OpCode(0xB4, "LDY", DirectPageIndexedWithX,                         &Cpu65816::executeLDY),
    OpCode(0xB5, "LDA", DirectPageIndexedWithX,                         &Cpu65816::executeLDA),
    OpCode(0xB6, "LDX", DirectPageIndexedWithY,                         &Cpu65816::executeLDX),
    OpCode(0xB7, "LDA", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeLDA),
    OpCode(0xB8, "CLV", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0xB9, "LDA", AbsoluteIndexedWithY,                           &Cpu65816::executeLDA),
    OpCode(0xBA, "TSX", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0xBB, "TYX", Implied,                                        &Cpu65816::executeTransfer),
    OpCode(0xBC, "LDY", AbsoluteIndexedWithX,                           &Cpu65816::executeLDY),
    OpCode(0xBD, "LDA", AbsoluteIndexedWithX,                           &Cpu65816::executeLDA),
    OpCode(0xBE, "LDX", AbsoluteIndexedWithY,                           &Cpu65816::executeLDX),
    OpCode(0xBF, "LDA", AbsoluteLongIndexedWithX,                       &Cpu65816::executeLDA),
    OpCode(0xC0, "CPY", Immediate,                                      &Cpu65816::executeCPXCPY),
    OpCode(0xC1, "CMP", DirectPageIndexedIndirectWithX,                 &Cpu65816::executeCMP),
    OpCode(0xC2, "REP", Immediate,                                      &Cpu65816::executeStatusReg),
    OpCode(0xC3, "CMP", StackRelative,                                  &Cpu65816::executeCMP),
    OpCode(0xC4, "CPY", DirectPage,                                     &Cpu65816::executeCPXCPY),
    OpCode(0xC5, "CMP", DirectPage,                                     &Cpu65816::executeCMP),
    OpCode(0xC6, "DEC", DirectPage,                                     &Cpu65816::executeINCDEC),
    OpCode(0xC7, "CMP", DirectPageIndirectLong,                         &Cpu65816::executeCMP),
    OpCode(0xC8, "INY", Implied,                                        &Cpu65816::executeINCDEC),
    OpCode(0xC9, "CMP", Immediate,                                      &Cpu65816::executeCMP),
    OpCode(0xCA, "DEX", Implied,                                        &Cpu65816::executeINCDEC),
    OpCode(0xCB, "WAI", Implied),
    OpCode(0xCC, "CPY", Absolute,                                       &Cpu65816::executeCPXCPY),
    OpCode(0xCD, "CMP", Absolute,                                       &Cpu65816::executeCMP),
    OpCode(0xCE, "DEC", Absolute,                                       &Cpu65816::executeINCDEC),
    OpCode(0xCF, "CMP", AbsoluteLong,                                   &Cpu65816::executeCMP),
    OpCode(0xD0, "BNE", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0xD1, "CMP", DirectPageIndirectIndexedWithY,                 &Cpu65816::executeCMP),
    OpCode(0xD2, "CMP", DirectPageIndirect,                             &Cpu65816::executeCMP),
    OpCode(0xD3, "CMP", StackRelativeIndirectIndexedWithY,              &Cpu65816::executeCMP),
    OpCode(0xD4, "PEI", StackDirectPageIndirect,                        &Cpu65816::executeStack),
    OpCode(0xD5, "CMP", DirectPageIndexedWithX,                         &Cpu65816::executeCMP),
    OpCode(0xD6, "DEC", DirectPageIndexedWithX,                         &Cpu65816::executeINCDEC),
    OpCode(0xD7, "CMP", DirectPageIndirectLongIndexedWithY,             &Cpu65816::executeCMP),
    OpCode(0xD8, "CLD", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0xD9, "CMP", AbsoluteIndexedWithY,                           &Cpu65816::executeCMP),
    OpCode(0xDA, "PHX", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0xDB, "STP", Implied),
    OpCode(0xDC, "JMP", AbsoluteIndirectLong,                           &Cpu65816::executeJumpReturn),
    OpCode(0xDD, "CMP", AbsoluteIndexedWithX,                           &Cpu65816::executeCMP),
    OpCode(0xDE, "DEC", AbsoluteIndexedWithX,                           &Cpu65816::executeINCDEC),
    OpCode(0xDF, "CMP", AbsoluteLongIndexedWithX,                       &Cpu65816::executeCMP),
    OpCode(0xE0, "CPX", Immediate,                                      &Cpu65816::executeCPXCPY),
    OpCode(0xE1, "SBC", DirectPageIndexedIndirectWithX),
    OpCode(0xE2, "SEP", Immediate,                                      &Cpu65816::executeStatusReg),
    OpCode(0xE3, "SBC", StackRelative),
    OpCode(0xE4, "CPX", DirectPage,                                     &Cpu65816::executeCPXCPY),
    OpCode(0xE5, "SBC", DirectPage),
    OpCode(0xE6, "INC", DirectPage,                                     &Cpu65816::executeINCDEC),
    OpCode(0xE7, "SBC", DirectPageIndirectLong),
    OpCode(0xE8, "INX", Implied,                                        &Cpu65816::executeINCDEC),
    OpCode(0xE9, "SBC", Immediate),
    OpCode(0xEA, "NOP", Implied),
    OpCode(0xEB, "XBA", Implied,                                        &Cpu65816::executeMisc),
    OpCode(0xEC, "CPX", Absolute,                                       &Cpu65816::executeCPXCPY),
    OpCode(0xED, "SBC", Absolute),
    OpCode(0xEE, "INC", Absolute,                                       &Cpu65816::executeINCDEC),
    OpCode(0xEF, "SBC", AbsoluteLong),
    OpCode(0xF0, "BEQ", ProgramCounterRelative,                         &Cpu65816::executeBranch),
    OpCode(0xF1, "SBC", DirectPageIndirectIndexedWithY),
    OpCode(0xF2, "SBC", DirectPageIndirect),
    OpCode(0xF3, "SBC", StackRelativeIndirectIndexedWithY),
    OpCode(0xF4, "PEA", StackAbsolute,                                  &Cpu65816::executeStack),
    OpCode(0xF5, "SBC", DirectPageIndexedWithX),
    OpCode(0xF6, "INC", DirectPageIndexedWithX,                         &Cpu65816::executeINCDEC),
    OpCode(0xF7, "SBC", DirectPageIndirectLongIndexedWithY),
    OpCode(0xF8, "SED", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0xF9, "SBC", AbsoluteIndexedWithY),
    OpCode(0xFA, "PLX", StackImplied,                                   &Cpu65816::executeStack),
    OpCode(0xFB, "XCE", Implied,                                        &Cpu65816::executeStatusReg),
    OpCode(0xFC, "JSR", AbsoluteIndexedIndirectWithX,                   &Cpu65816::executeJumpReturn),
    OpCode(0xFD, "SBC", AbsoluteIndexedWithX),
    OpCode(0xFE, "INC", AbsoluteIndexedWithX,                           &Cpu65816::executeINCDEC),
    OpCode(0xFF, "SBC", AbsoluteLongIndexedWithX)
};

#endif // OPCODE_TABLE_HPP

